kind: pipeline
name: default

steps:  
  - name: test_pull_request
    image: docker
    commands:
      - docker build -t squidex/squidex-identity:test_pull_request .
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
    when:
      event:
        - pull_request

  - name: build_dev
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t squidex/squidex-identity:dev .
      - docker push squidex/squidex-identity:dev
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
    secrets: [ docker_username, docker_password ]
    when:
      event:
        - push
      branch:
        - master

  - name: build_release
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t squidex/squidex-identity:latest -t squidex/squidex-identity:$${DRONE_TAG} .
      - docker push squidex/squidex-identity:latest
      - docker push squidex/squidex-identity:$${DRONE_TAG}
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
    secrets: [ docker_username, docker_password ]
    when:
      event:
        - tag

  - name: slack
    image: plugins/slack
    template: >
      {{#success build.status}}
        Squidex Identity build {{build.number}} succeeded. Good job.
      {{else}}
        Squidex Identity build {{build.number}} failed. Fix me please.
      {{/success}}
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - failure
        - success

  - name: cleanup
    image: docker
    commands:
      - docker system prune -f
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
    when:
      status:
        - failure
      
volumes:
  - name: docker1
    host:
      path: /var/run/docker.sock
  - name: docker2
    host:
      path: /var/lib/docker